name: NinjaOne Test Automation

on:
  schedule:
    # Runs at 13:00 UTC (9:00 AM EST) every day
    - cron: '0 13 * * *'
  workflow_dispatch:  # Keeps manual trigger option

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Clean install dependencies
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Removing node_modules if exists"
        rm -rf node_modules
        echo "Removing package-lock.json if exists"
        rm -f package-lock.json
        echo "Installing dependencies with npm install"
        npm install
        echo "Running npm ci"
        npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium

    - name: Create directories for artifacts
      run: |
        mkdir -p test-results
        mkdir -p playwright-report
        mkdir -p screenshots

    - name: Create .env file
      run: |
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
        echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env

    - name: Create token.json
      run: |
        echo '${{ secrets.GMAIL_TOKEN }}' > token.json

    - name: Run Cucumber tests with HTML report
      run: |
        echo "Running Cucumber tests..."
        xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" npx cucumber-js \
          src/test/features/login.feature \
          --format progress-bar \
          --format html:playwright-report/cucumber-report.html \
          --format json:test-results/cucumber-report.json \
          --format summary \
          --format @cucumber/pretty-formatter \
          --publish-quiet
      env:
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        DEBUG: pw:api
        PLAYWRIGHT_HEADLESS: 1
      continue-on-error: true

    - name: List artifacts
      if: always()
      run: |
        echo "Contents of current directory:"
        ls -la
        echo "Contents of test-results:"
        ls -la test-results || echo "test-results not found"
        echo "Contents of playwright-report:"
        ls -la playwright-report || echo "playwright-report not found"
        echo "Contents of screenshots:"
        ls -la screenshots || echo "screenshots not found"

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/
          playwright-report/
          screenshots/
        retention-days: 30

    - name: Deploy report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./playwright-report
        publish_branch: gh-pages 